apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: signadot/backstage-sample-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
          envFrom:
            - secretRef:
                name: postgres-credentials
          env:
            - name: NODE_ENV
              value: development
