name: producer-sbx
spec:
  labels:
    demo: "kafka"
  cluster: "@{cluster}"
  forks:
  - forkOf:
      kind: Deployment
      name: producer
      namespace: kafka-demo
  defaultRouteGroup:
    endpoints:
    - name: frontend
      target: http://frontend.kafka-demo.svc:4000