apiVersion: v1
kind: ServiceAccount
metadata:
  name: producer
  namespace: kafka-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: kafka-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
      annotations:
        sidecar.signadot.com/inject: "true"
    spec:
      serviceAccountName: producer
      enableServiceLinks: false
      containers:
        - name: producer
          image: signadot/kafka-demo:latest
          command:
            - "npm"
            - "run"
            - "producer"
          env:
            - name: PRODUCER_PORT
              value: "40001"
            - name: BASELINE_NAME
              value: "producer"
            - name: KAFKA_ADDR
              value: "kafka-headless.kafka-demo.svc:9092"
            - name: KAFKAJS_NO_PARTITIONER_WARNING
              value: "1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 40001
          securityContext:
            # Run with the "node" user
            runAsUser: 1000
            runAsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: producer
  namespace: kafka-demo
  labels:
    app: producer
spec:
  type: ClusterIP
  selector:
    app: producer
  ports:
    - port: 4001
      targetPort: 40001
      name: http
