apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  # namespace: your-namespace # Optional: Uncomment and specify if deploying to a specific namespace
type: Opaque
data:
  # Values are base64 encoded.
  # POSTGRES_USER: echo -n 'temporal' | base64 -> dGVtcG9yYWw=
  # POSTGRES_PASSWORD: echo -n 'temporal' | base64 -> dGVtcG9yYWw=
  POSTGRES_USER: dGVtcG9yYWw=
  POSTGRES_PASSWORD: dGVtcG9yYWw=