apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  # namespace: your-namespace # Optional: Uncomment and specify if deploying to a specific namespace
  labels:
    app: postgresql
spec:
  accessModes:
    - ReadWriteOnce # Suitable for a single database instance
  resources:
    requests:
      storage: 10Gi # Adjust storage size as needed
  # storageClassName: your-storage-class # Important: Uncomment and specify if you don't have a default StorageClass in your K8s cluster, or if you want to use a specific one.